#  This file is part of R-Link.
# 
#     R-Link is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     R-Link is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with R-Link.  If not, see <http://www.gnu.org/licenses/>.
# # Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LoadAimmsAndOpenProject <- function(path, projectPath) {
    .Call('aimms4r_LoadAimmsAndOpenProject', PACKAGE = 'aimms4r', path, projectPath)
}

LoadAimms <- function(path) {
    .Call('aimms4r_LoadAimms', PACKAGE = 'aimms4r', path)
}

OpenProject <- function(projectPath) {
    .Call('aimms4r_OpenProject', PACKAGE = 'aimms4r', projectPath)
}

CloseProject <- function() {
    .Call('aimms4r_CloseProject', PACKAGE = 'aimms4r')
}

TestLoadedApi <- function(path) {
    .Call('aimms4r_TestLoadedApi', PACKAGE = 'aimms4r', path)
}

GetData <- function(identifierName) {
    .Call('aimms4r_GetData', PACKAGE = 'aimms4r', identifierName)
}

SetData <- function(data, identifierName) {
    invisible(.Call('aimms4r_SetData', PACKAGE = 'aimms4r', data, identifierName))
}

