# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LoadAimmsAndOpenProject <- function(path, projectPath) {
    .Call('aimms4r_LoadAimmsAndOpenProject', PACKAGE = 'aimms4r', path, projectPath)
}

LoadAimms <- function(path) {
    .Call('aimms4r_LoadAimms', PACKAGE = 'aimms4r', path)
}

OpenProject <- function(projectPath) {
    .Call('aimms4r_OpenProject', PACKAGE = 'aimms4r', projectPath)
}

CloseProject <- function() {
    .Call('aimms4r_CloseProject', PACKAGE = 'aimms4r')
}

TestLoadedApi <- function(path) {
    .Call('aimms4r_TestLoadedApi', PACKAGE = 'aimms4r', path)
}

GetData <- function(identifierName) {
    .Call('aimms4r_GetData', PACKAGE = 'aimms4r', identifierName)
}

SetData <- function(data, identifierName, modeForUnknownElements = 0L) {
    invisible(.Call('aimms4r_SetData', PACKAGE = 'aimms4r', data, identifierName, modeForUnknownElements))
}

